apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend-service
spec:
  type: NodePort
  ports:
    - targetPort: 27017
      port: 27017
  selector:
    app: db-pod
