apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: db-deploy
spec:
  selector:
    matchLabels:
      app: db-pod
  template:
    metadata:
      name: db-pod
      labels:
        app: db-pod
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: db-pod
          image: mongo
          command:
            - mongod
            - '--bind_ip'
            - '0.0.0.0'
          ports:
            - containerPort: 27017
          envFrom:
            - secretRef:
                name: mongo-creds
          livenessProbe:
            exec:
              command:
                - echo
                - -e
                - '--eval "db.adminCommand(''ping'')"'
                - \|
                - xargs
                - mongo
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - echo
                - -e
                - '--eval "db.adminCommand(''ping'')"'
                - \|
                - xargs
                - mongo
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb-service
spec:
  type: ClusterIP
  ports:
    - targetPort: 27017
      port: 27017
  selector:
    app: db-pod
