apiVersion: v1
kind: Secret
metadata:
  name: mongo-creds
stringData:
  MONGO_INITDB_ROOT_USERNAME: max
  MONGO_INITDB_ROOT_PASSWORD: secret
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-db-con-creds
stringData:
  MONGODB_USERNAME: max
  MONGODB_PASSWORD: secret
